// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7Z0-yvQklDMOTHDFaum3YbeVdYsLL_q4',
    appId: '1:403086268327:web:9b7813c840f373714e8882',
    messagingSenderId: '403086268327',
    projectId: 'just-chat-beta-001',
    authDomain: 'just-chat-beta-001.firebaseapp.com',
    storageBucket: 'just-chat-beta-001.appspot.com',
    measurementId: 'G-Y3JL1FQ81D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqU4ccMbpKLgFUT8OsHram2lUIQ_w8aJg',
    appId: '1:403086268327:android:a42ecb89d07109ba4e8882',
    messagingSenderId: '403086268327',
    projectId: 'just-chat-beta-001',
    storageBucket: 'just-chat-beta-001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLj56Pk70jOvsLTpxql9bEs2kOfLqdHAE',
    appId: '1:403086268327:ios:8fbff4892d24ddf04e8882',
    messagingSenderId: '403086268327',
    projectId: 'just-chat-beta-001',
    storageBucket: 'just-chat-beta-001.appspot.com',
    iosClientId: '403086268327-hb17uepmi9t6cs73b2sf70p20tutc9du.apps.googleusercontent.com',
    iosBundleId: 'com.kwejibo.justChatBeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLj56Pk70jOvsLTpxql9bEs2kOfLqdHAE',
    appId: '1:403086268327:ios:8fbff4892d24ddf04e8882',
    messagingSenderId: '403086268327',
    projectId: 'just-chat-beta-001',
    storageBucket: 'just-chat-beta-001.appspot.com',
    iosClientId: '403086268327-hb17uepmi9t6cs73b2sf70p20tutc9du.apps.googleusercontent.com',
    iosBundleId: 'com.kwejibo.justChatBeta',
  );
}
